# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Code\EVEFarming\Bind.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Bind(object):
    def setupUi(self, Bind):
        Bind.setObjectName("Bind")
        Bind.resize(450, 750)
        self.label = QtWidgets.QLabel(Bind)
        self.label.setGeometry(QtCore.QRect(20, 10, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lwWindows = QtWidgets.QListWidget(Bind)
        self.lwWindows.setGeometry(QtCore.QRect(20, 50, 411, 571))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lwWindows.setFont(font)
        self.lwWindows.setObjectName("lwWindows")
        self.btnRefresh = QtWidgets.QPushButton(Bind)
        self.btnRefresh.setGeometry(QtCore.QRect(90, 640, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnRefresh.setFont(font)
        self.btnRefresh.setObjectName("btnRefresh")
        self.btnOK = QtWidgets.QPushButton(Bind)
        self.btnOK.setGeometry(QtCore.QRect(240, 640, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnOK.setFont(font)
        self.btnOK.setObjectName("btnOK")
        self.label_2 = QtWidgets.QLabel(Bind)
        self.label_2.setGeometry(QtCore.QRect(330, 720, 101, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Bind)
        QtCore.QMetaObject.connectSlotsByName(Bind)

    def retranslateUi(self, Bind):
        _translate = QtCore.QCoreApplication.translate
        Bind.setWindowTitle(_translate("Bind", "选择游戏窗口"))
        self.label.setText(_translate("Bind", "选择游戏窗口 (标题--句柄)"))
        self.btnRefresh.setText(_translate("Bind", "刷 新"))
        self.btnOK.setText(_translate("Bind", "确 定"))
        self.label_2.setText(_translate("Bind", "---- by tenting"))
